import type { Restaurant, MenuItem, User } from "@/types"

export const mockRestaurants: Restaurant[] = [
  {
    id: "1",
    name: "Pizza Palace",
    description: "Authentic Italian pizzas made with fresh ingredients",
    image: "/bustling-pizza-restaurant.png",
    cuisine: ["Italian", "Pizza"],
    rating: 4.5,
    deliveryTime: "25-35 min",
    deliveryFee: 2.99,
    minimumOrder: 15,
    isOpen: true,
    address: "123 Main St, City",
    phone: "+1234567890",
    ownerId: "owner1",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Burger Barn",
    description: "Juicy burgers and crispy fries",
    image: "/burger-restaurant.png",
    cuisine: ["American", "Burgers"],
    rating: 4.2,
    deliveryTime: "20-30 min",
    deliveryFee: 1.99,
    minimumOrder: 12,
    isOpen: true,
    address: "456 Oak Ave, City",
    phone: "+1234567891",
    ownerId: "owner2",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Sushi Zen",
    description: "Fresh sushi and Japanese cuisine",
    image: "/bustling-sushi-restaurant.png",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.8,
    deliveryTime: "30-40 min",
    deliveryFee: 3.99,
    minimumOrder: 20,
    isOpen: true,
    address: "789 Pine St, City",
    phone: "+1234567892",
    ownerId: "owner3",
    createdAt: new Date(),
  },
]

export const mockMenuItems: MenuItem[] = [
  // Pizza Palace items
  {
    id: "1",
    restaurantId: "1",
    name: "Margherita Pizza",
    description: "Classic pizza with tomato sauce, mozzarella, and fresh basil",
    price: 14.99,
    image: "/margherita-pizza.png",
    category: "Pizza",
    isAvailable: true,
    ingredients: ["Tomato sauce", "Mozzarella", "Fresh basil", "Olive oil"],
  },
  {
    id: "2",
    restaurantId: "1",
    name: "Pepperoni Pizza",
    description: "Traditional pizza with pepperoni and mozzarella cheese",
    price: 16.99,
    image: "/pepperoni-pizza.png",
    category: "Pizza",
    isAvailable: true,
    ingredients: ["Tomato sauce", "Mozzarella", "Pepperoni"],
  },
  // Burger Barn items
  {
    id: "3",
    restaurantId: "2",
    name: "Classic Cheeseburger",
    description: "Beef patty with cheese, lettuce, tomato, and special sauce",
    price: 12.99,
    image: "/classic-cheeseburger.png",
    category: "Burgers",
    isAvailable: true,
    ingredients: ["Beef patty", "Cheese", "Lettuce", "Tomato", "Special sauce"],
  },
  {
    id: "4",
    restaurantId: "2",
    name: "Crispy Fries",
    description: "Golden crispy french fries",
    price: 4.99,
    image: "/crispy-french-fries.png",
    category: "Sides",
    isAvailable: true,
  },
  // Sushi Zen items
  {
    id: "5",
    restaurantId: "3",
    name: "Salmon Roll",
    description: "Fresh salmon with avocado and cucumber",
    price: 8.99,
    image: "/salmon-sushi-roll.png",
    category: "Rolls",
    isAvailable: true,
    ingredients: ["Fresh salmon", "Avocado", "Cucumber", "Sushi rice", "Nori"],
  },
  {
    id: "6",
    restaurantId: "3",
    name: "Tuna Sashimi",
    description: "Fresh tuna sashimi (6 pieces)",
    price: 12.99,
    image: "/tuna-sashimi.png",
    category: "Sashimi",
    isAvailable: true,
    ingredients: ["Fresh tuna"],
  },
]

export const mockUsers: User[] = [
  {
    id: "admin",
    email: "admin@example.com",
    name: "Admin User",
    role: "admin",
    createdAt: new Date(),
  },
  {
    id: "customer1",
    email: "customer@example.com",
    name: "John Customer",
    role: "customer",
    phone: "+1234567890",
    createdAt: new Date(),
  },
  {
    id: "rider1",
    email: "rider@example.com",
    name: "Mike Rider",
    role: "rider",
    phone: "+1234567891",
    createdAt: new Date(),
  },
  {
    id: "owner1",
    email: "owner@example.com",
    name: "Sarah Owner",
    role: "restaurant",
    phone: "+1234567892",
    createdAt: new Date(),
  },
]
